### K- Fold Cross Validation
Assume you have a dataset and set k = 5:
1. Shuffle the data and split it into 5 equal-sized folds.
2. For each fold:
  - Use 1 fold as the test set
  - Use the remaining 4 folds as the training set
  - Train the model and evaluate it
3. Repeat this k times, each time with a DIFFERENT test fold.

4. Finally, average the evaluation scores across all k runs.

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [31]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [33]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [34]:
lr = LogisticRegression()
get_score(lr, X_train, X_test, y_train, y_test)

e:\VS_code\scikit-learn\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9462962962962963

In [35]:
svm = SVC()
get_score(svm, X_train, X_test, y_train, y_test)

0.9777777777777777

In [36]:
rf = RandomForestClassifier()
get_score(rf, X_train, X_test, y_train, y_test)

0.95

#### Using K-Fold Validation

In [37]:
from sklearn.model_selection import cross_val_score

In [47]:
scores = cross_val_score( LogisticRegression(), digits.data, digits.target, cv=4 )  ## cv = folds
print(scores)
print(scores.mean() )

[0.93555556 0.90423163 0.94877506 0.91759465]
0.9265392229646128


e:\VS_code\scikit-learn\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
e:\VS_code\scikit-learn\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
 

In [46]:
scores = cross_val_score(SVC(), digits.data, digits.target, cv=4)
print(scores)
print(scores.mean() )

[0.96222222 0.96659243 0.98218263 0.95100223]
0.9654998762682504


In [45]:
scores = cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=4)
print(scores)
print(scores.mean())

[0.94222222 0.922049   0.9688196  0.93095768]
0.9410121257114575
